config/routes.rb
Performance::Application.routes.draw do
  resources :analyser_classes
  resources :analyser_types
  resources :create_analyser_types
  resources :form_configs
  match 'eqaform/:form_builder_id' => 'form_configs#create_form'
  
  resources :form_configs do
    resources :form_configs
  end
  
  resources :form_builders
  devise_for :admins
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :eqa_schemes
  
  resources :change_loggings 
  match 'change_loggings_deleteall' => 'change_loggings#deleteall'
  
  resources :eqas
  match 'create_eqa_form' => 'eqas#create_eqa_form'
  
  resources :quality_specifications 
  resources :quality_specification_imports
  
  
  
  get 'test_codes/add_ams_test_codes', to: 'test_codes#add_ams_test_codes'
  get 'test_codes/ams_test_codes', to: 'test_codes#ams_test_codes'
  get "test_codes/new"
  get "test_codes/create"
  match 'test_generate' => 'test_codes#generate'
  resources :test_code_imports
  resources :test_codes
  
  match 'sigmacalc' => 'sigmas#calculateSigmas'
  match 'sigmaplot' => 'sigmas#plotSigmas'
  match 'alltestssigma' => 'sigmas#allTestsSigmaPlot'
  resources :sigmas
  
  get 'iqc_data/analyser_iqc', to: 'iqc_data#analyser_iqc'
  get 'iqc_data/view', to: 'iqc_data#view'
  get 'iqc_data/show_analyser/', to: 'iqc_data#show_analyser_view'
  post 'iqc_data/show_analyser/', to: 'iqc_data#show_analyser_view'
  get 'iqc_data/show_iqc_material_view', to: 'iqc_data#show_iqc_material_view'
  get 'iqc_data/show_test_view', to: 'iqc_data#show_test_view'
  
  resources :iqc_data
  
  get 'iqcs/add_ams_qc', to: 'iqcs#add_ams_qc'
  get 'iqcs/ams_qc', to: 'iqcs#ams_qc'
  
  resources :iqcs
  resources :targets
  
  match 'transfer_qc' => 'iqc_data#transfer'
  
  match 'iqc_data/test_view' => 'iqc_data#test_view'
  match 'iqc_data/view_iqc_stats' => 'iqc_data#view_iqc_stats'
  match 'iqc_data/view_iqc_stats' => 'iqc_data#view_iqc_stats'
  match 'iqc_data/view_analyser_stats' => 'iqc_data#view_analyser_stats'
  
  
  match 'qc_generate' => 'iqcs#generate'
  
  get 'analysers/add_ams_analyser', to: 'analysers#add_ams_analyser'
  get 'analysers/ams_analyser', to: 'analysers#ams_analyser'
  match 'analyser_generate' => 'analysers#generate'
  resources :analysers
  
  resources :imported_file
  resources :imported_qc

  get "home/index"
  match "home/index" =>"home#index"
  root :to => "home#index"

end

app/models/analyser.rb
class Analyser < ActiveRecord::Base
  attr_accessible :AnalyserLocation, :AnalyserName, :AnalyserNote, :analyser_types_id
  
  has_many :iqc_datum
  has_many :eqas
  has_one :analyser_type
  
  def self.generate
    @generated_analysers= ImportedQc.all(:group => :analyser)
    
    @generated_analysers.each do |qc|
      qc = Analyser.new(:AnalyserName => qc.analyser, :AnalyserNote => "Auto generated", :analyser_types_id => 1) 
      qc.save
    end
    
  end
  
  def self.add_imported_analyser(analyser)
    qc = Analyser.new(:AnalyserName => analyser, :AnalyserNote => "Auto generated", :analyser_types_id => 1) 
    qc.save
  
  end
  
end

app/models/analyser_type.rb
class AnalyserType < ActiveRecord::Base
  attr_accessible :analyser_type_name, :analyser_type_description, :analyser_picture, :analyser_classes_id
  
  has_many :analysers
  
  has_attached_file :analyser_picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
end

app/controllers/analysers_controller.rb
class AnalysersController < ApplicationController
  
  before_filter :authenticate_user!
  
	# GET /analysers
  # GET /analysers.json
  def index
    @analysers = Analyser.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @analysers }
    end
  end

def ams_analyser
    @iqc = Analyser.all
    @ams = ImportedQc.group("analyser")
    
    ids = @iqc.map{|x| x.AnalyserName}
    @diffs = @ams.reject{|x| ids.include? x.analyser}
    puts @diffs
    puts ids
end

def add_ams_analyser
    @analyser = Analyser.add_imported_analyser(params[:analyser])
  
end


  # GET /analysers/1
  # GET /analysers/1.json
  def show
    @analysers = Analyser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @analysers }
    end
  end

  def generate
    @generated_analysers = Analyser.generate
  
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /analysers/new
  # GET /analysers/new.json
  def new
    @analysers = Analyser.new
   

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @analysers }
    end
  end

  # GET /analysers/1/edit
  def edit
    @analysers = Analyser.find(params[:id])
  end

  # POST /analysers
  # POST /analysers.json
  def create
    @analysers = Analyser.new(params[:analyser])

    respond_to do |format|
      if @analysers.save
        changeLogging = ChangeLogging.new(:logRecord => 'New analyser created', :users_id => current_user.id)
        changeLogging.save
        
        format.html { redirect_to @analysers, notice: 'analysers was successfully created.' }
        format.json { render json: @analysers, status: :created, location: @analysers }
      else
        format.html { render action: "new" }
        format.json { render json: @analysers.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /analysers/1
  # PUT /analysers/1.json
  def update
    @analysers = Analyser.find(params[:id])

    respond_to do |format|
      if @analysers.update_attributes(params[:analyser])
        changeLogging = ChangeLogging.new(:logRecord => 'Analyser updated' + params[:analyser].to_s, :users_id => current_user.id)
        changeLogging.save
        
        format.html { redirect_to @analysers, notice: 'analysers was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @analysers.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /analysers/1
  # DELETE /analysers/1.json
  def destroy
    @analysers = Analyser.find(params[:id])
    @analysers.destroy
    
    changeLogging = ChangeLogging.new(:logRecord => 'Analyser deleted' + params[:id], :users_id => current_user.id)
    changeLogging.save

    respond_to do |format|
      format.html { redirect_to analysers_url }
      format.json { head :no_content }
    end
  end
end

app/views/analysers/_form.html.erb
<%= form_for@analysers, :html => {:class => "form-horizontal well"} do |f| %>
  <% if @analysers.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@analysers.errors.count, "error") %> prohibited this analyser from being saved:</h2>

      <ul>
      <% @analysers.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<legend>Add/Edit Quality Specification</legend>
<fieldset>
	<div class="control-group">
		<%= label_tag(:AnalyserName, "Analyser Name", :class =>"control-label") %>
		<div class="controls">
			<%= f.text_field :AnalyserName %>
		</div>
	</div>

	<div class="control-group">
		<%= label_tag(:AnalyserNote, "Analyser Notes", :class =>"control-label") %>
		<div class="controls">
			<%= f.text_field :AnalyserNote %>
		</div>
	</div>

	<div class="control-group">
		<%= label_tag(:AnalyserLocation, "Analyser Location", :class =>"control-label") %>
		<div class="controls">
			<%= f.text_field :AnalyserLocation %>
		</div>
	</div>
	
	<div class="control-group">
		<%= label_tag(:analyser_types_id, "Analyser Type", :class =>"control-label") %>
		<div class="controls">
			<%= select("analyser", "analyser_types_id", AnalyserType.all.collect {|p| [ p.analyser_type_name, p.id ] }, {:include_blank => 'None'})%>
		</div>
	</div>


		<div class="form-actions">
			<%= f.submit :class => "btn-primary" %>
		</div>
	<fieldset>
<% end %>

app/views/analysers/add_ams_analyser.html.erb
<% if @iqc == false %>
	<div id="error_explanation">
		<div class="alert alert-error">
		Error Adding Record
		</div>
	</div>
<% else %>
<div class="alert alert-success">
Record Imported
</div>
<% end %>

app/views/analysers/ams_analyser.html.erb
<div class="row">
  <div class="span6">
	<span class="label label-success">Analysers In System</span></br>
	<ul>
  	<% @iqc.each do |iqc| %>
		<li><%=iqc.AnalyserName%></li>
	<%end%>
	</ul>
  </div>

<div class="span6">
	<span class="label label-success">Analysers in AMS</span></br>
	<ul>
  	<% @ams.each do |ams| %>
		<li><%=ams.analyser%></li>
	<%end%>
	</ul>
  </div>
</div>
<div class="row">
	<% if @diffs.empty? %>
	<div class="alert alert-success">
		No differences found
		</div>
		<%else%>
		Differences: <%=@diffs%>
		<%= link_to "Add unimported Analyser",  analysers_add_ams_analyser_path(:analyser => @diffs[0].analyser) %>
		<%end%>	
</div>

app/views/analysers/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @analysers %> |
<%= link_to 'Back', analysers_path %>

app/views/analysers/generate.html.erb
Auto Generated the following Analysers:<br>
<table class="table table-bordered table-striped table-condensed table-hover">
  <tr>
    <th>Analyser</th>
  </tr>

<% @generated_analysers.each do |qc| %>
  <tr>
	<td><%= qc.analyser %> </td>
  </tr>
<% end %>
</table>

app/views/analysers/index.html.erb
<h2>Listing analysers</h2>

<table class="table table-bordered table-striped table-condensed table-hover">
<thead>
  <tr>
    <th>Analyser Name</th>
    <th scope="col" class="rounded-q1">Analyser Notes</th>
    <th scope="col" class="rounded-q2">Analyser Location</th>
    <th scope="col" class="rounded-q2">Created Date/Time</th>
    <th scope="col" class="rounded-q2">Editing</th>
    <th scope="col" class="rounded-q2"></th>
    <th scope="col" class="rounded-q2"></th>
  </tr>
</thead>

<tfoot>
    	<tr>
        	<td colspan="6" class="rounded-foot-left"><em>Analyser management functions</em></td>
        	<td class="rounded-foot-right">&nbsp;</td>
        </tr>
    </tfoot>

<% @analysers.each do |analyser| %>
  <tr>
    <td><%= analyser.AnalyserName %></td>
    <td><%= analyser.AnalyserNote %></td>
    <td><%= analyser.AnalyserLocation %></td>
    <td><%= analyser.created_at %></td>
    <td><%= link_to 'Show', analyser, :class => "btn btn-primary btn-small" %></td>
    <td><%= link_to 'Edit', edit_analyser_path(analyser), :class => "btn btn-info btn-small" %></td>
    <td><%= link_to 'Destroy', analyser, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-small" %></td>
  </tr>
<% end %>
</table>

<%= link_to 'New Analyser', new_analyser_path, :class => "btn btn-primary" %></td>

app/views/analysers/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', analysers_path %>

app/views/analysers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Analyser Name:</b>
  <%= @analysers.AnalyserName %>
</p>

<p>
  <b>Notes:</b>
  <%= @analysers.AnalyserNote %>
</p>

<p>
  <b>Location:</b>
  <%= @analysers.AnalyserLocation %>
</p>

<p>
  <b>Created At:</b>
  <%= @analysers.created_at %>
</p>

<p>
  <b>Updated At:</b>
  <%= @analysers.updated_at %>
</p>


<%= link_to 'Edit', edit_analyser_path(@analysers) %> |
<%= link_to 'Back', analysers_path %>