config/routes.rb
Performance::Application.routes.draw do
  resources :analyser_classes
  resources :analyser_types
  resources :create_analyser_types
  resources :form_configs
  match 'eqaform/:form_builder_id' => 'form_configs#create_form'
  
  resources :form_configs do
    resources :form_configs
  end
  
  resources :form_builders
  devise_for :admins
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :eqa_schemes
  
  resources :change_loggings 
  match 'change_loggings_deleteall' => 'change_loggings#deleteall'
  
  resources :eqas
  match 'create_eqa_form' => 'eqas#create_eqa_form'
  
  resources :quality_specifications 
  resources :quality_specification_imports
  
  
  
  get 'test_codes/add_ams_test_codes', to: 'test_codes#add_ams_test_codes'
  get 'test_codes/ams_test_codes', to: 'test_codes#ams_test_codes'
  get "test_codes/new"
  get "test_codes/create"
  match 'test_generate' => 'test_codes#generate'
  resources :test_code_imports
  resources :test_codes
  
  match 'sigmacalc' => 'sigmas#calculateSigmas'
  match 'sigmaplot' => 'sigmas#plotSigmas'
  match 'alltestssigma' => 'sigmas#allTestsSigmaPlot'
  resources :sigmas
  
  get 'iqc_data/analyser_iqc', to: 'iqc_data#analyser_iqc'
  get 'iqc_data/view', to: 'iqc_data#view'
  get 'iqc_data/show_analyser/', to: 'iqc_data#show_analyser_view'
  post 'iqc_data/show_analyser/', to: 'iqc_data#show_analyser_view'
  get 'iqc_data/show_iqc_material_view', to: 'iqc_data#show_iqc_material_view'
  get 'iqc_data/show_test_view', to: 'iqc_data#show_test_view'
  
  resources :iqc_data
  
  get 'iqcs/add_ams_qc', to: 'iqcs#add_ams_qc'
  get 'iqcs/ams_qc', to: 'iqcs#ams_qc'
  
  resources :iqcs
  resources :targets
  
  match 'transfer_qc' => 'iqc_data#transfer'
  
  match 'iqc_data/test_view' => 'iqc_data#test_view'
  match 'iqc_data/view_iqc_stats' => 'iqc_data#view_iqc_stats'
  match 'iqc_data/view_iqc_stats' => 'iqc_data#view_iqc_stats'
  match 'iqc_data/view_analyser_stats' => 'iqc_data#view_analyser_stats'
  
  
  match 'qc_generate' => 'iqcs#generate'
  
  get 'analysers/add_ams_analyser', to: 'analysers#add_ams_analyser'
  get 'analysers/ams_analyser', to: 'analysers#ams_analyser'
  match 'analyser_generate' => 'analysers#generate'
  resources :analysers
  
  resources :imported_file
  resources :imported_qc

  get "home/index"
  match "home/index" =>"home#index"
  root :to => "home#index"

end

app/models/iqc.rb
class Iqc < ActiveRecord::Base
  attr_accessible :assigned, :manufacturer, :name, :notes, :id, :code, :lotno, :expirydate, :dateinuse, :datereconstituted, :numberofaliquots, :storagelocation, :storagetemp, :users_id
  
  belongs_to :testCode
  has_many :iqcDatums
  
  def self.generate
    @generated_qc_lots= ImportedQc.all(:group => :qclot)
    
    @generated_qc_lots.each do |qc|
      qc = Iqc.new(:name => qc.qclot, :notes => "Auto generated", :lotno => qc.qclot) 
      qc.save
    end
    
  end
  
  def self.add_imported_qc(qclot)
    qc = Iqc.new(:name => qclot, :notes => "Auto generated", :lotno => qclot) 
    qc.save
  
  end
  
end

app/controllers/iqcs_controller.rb
class IqcsController < ApplicationController
  
  before_filter :authenticate_user!
  
  
# GET /iqc
  # GET /iqc.json
  def index
    @iqc = Iqc.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @iqc }
    end
  end
  
  def ams_qc
    @iqc = Iqc.all
    @ams = ImportedQc.group("qclot")
    
    ids = @iqc.map{|x| x.lotno}
    @diffs = @ams.reject{|x| ids.include? x.qclot}
    puts @diffs
    puts ids
  end
  
  def add_ams_qc
    @iqc = Iqc.add_imported_qc(params[:qc_lot])
  
  end

  # GET /iqc/1
  # GET /iqc/1.json
  def show
    @iqc = Iqc.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @iqc }
    end
  end
  
  def generate
    @geniqc = Iqc.generate
    
    respond_to do |format|
      format.html # new.html.erb
    end
    
  end

  # GET /iqc/new
  # GET /iqc/new.json
  def new
    @iqc = Iqc.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @iqc }
    end
  end

  # GET /iqc/1/edit
  def edit
    @iqc = Iqc.find(params[:id])
  end

  # POST /iqc
  # POST /iqc.json
  def create
    @iqc = Iqc.new(params[:iqc])

    respond_to do |format|
      if @iqc.save
        @iqc.users_id = current_user.id
        changeLogging = ChangeLogging.new(:logRecord => 'QC Material Created', :users_id => current_user.id)
        changeLogging.save
        
        format.html { redirect_to @iqc, notice: 'IQC was successfully created.' }
        format.json { render json: @iqc, status: :created, location: @iqc }
      else
        format.html { render action: "new" }
        format.json { render json: @iqc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /iqc/1
  # PUT /iqc/1.json
  def update
    @iqc = Iqc.find(params[:id])

    respond_to do |format|
      if @iqc.update_attributes(params[:iqc])
        
        changeLogging = ChangeLogging.new(:logRecord => 'IQC Material updated: ' + params[:iqc].to_s, :users_id => current_user.id)
        changeLogging.save
        format.html { redirect_to @iqc, notice: 'IQC was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @iqc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /iqc/1
  # DELETE /iqc/1.json
  def destroy
    @iqc = Iqc.find(params[:id])
    @iqc.destroy
    changeLogging = ChangeLogging.new(:logRecord => 'IQC Material Deleted: '+ params[:id], :users_id => current_user.id)
    changeLogging.save

    respond_to do |format|
      format.html { redirect_to iqcs_url }
      format.json { head :no_content }
    end
  end
end

app/views/iqcs/_form.html.erb
<%= form_for @iqc, :html => {:class => "form-horizontal well"} do |f| %>

  <% if @iqc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@iqc.errors.count, "error") %> prohibited this iqc from being saved:</h2>

      <ul>
      <% @iqc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<legend>Add/Edit IQC material </legend>
<fieldset>
	<div class="control-group">
		<%= label_tag(:name, "IQC Material Name", :class =>"control-label") %>
		<div class="controls">
			<%= f.text_field :name%>
		</div>
	</div>

	<div class="control-group">
		<%= label_tag(:manufacturer, "Manufacturer", :class =>"control-label") %>
		<div class="controls">
			<%= f.text_field :manufacturer%>
		</div>
	</div>	

	<div class="control-group">
		<%= label_tag(:notes, "Notes", :class =>"control-label") %>
		<div class="controls">
			<%= f.text_field :notes%>
		</div>
	</div>

	<div class="control-group">
		<%= label_tag(:assigned, "Does this QC come with assigned values", :class =>"control-label") %>
		<div class="controls">
			<%= f.check_box :assigned%>
		</div>
	</div>
	
	<div class="control-group">
		<%= label_tag(:code, "IQC Code", :class =>"control-label") %>
		<div class="controls">
			<%= f.text_field :code%>
		</div>
	</div> 

	<div class="control-group">
		<%= label_tag(:lotno, "Lot Number", :class =>"control-label") %>
		<div class="controls">
			<%= f.text_field :lotno%>
		</div>
	</div>

 	<div class="control-group">
		<%= label_tag(:expirydate, "Expiry date", :class =>"control-label") %>
		<div class="controls">
			<%= f.text_field :expirydate%>
		</div>
	</div>

 	<div class="control-group">
		<%= label_tag(:dateinuse, "Date in Use", :class =>"control-label") %>
		<div class="controls">
			<%= f.text_field :dateinuse%>
		</div>
	</div>
  
 	<div class="control-group">
		<%= label_tag(:datereconstituted, "Date Reconstituted", :class =>"control-label") %>
		<div class="controls">
			<%= f.text_field :datereconstituted%>
		</div>
	</div>

 	<div class="control-group">
		<%= label_tag(:numberofaliquots, "Number of Aliquots", :class =>"control-label") %>
		<div class="controls">
			<%= f.text_field :numberofaliquots%>
		</div>
	</div>
 
 	<div class="control-group">
		<%= label_tag(:storagelocation, "Storage Location", :class =>"control-label") %>
		<div class="controls">
			<%= f.text_field :storagelocation%>
		</div>
	</div>

 	<div class="control-group">
		<%= label_tag(:storagetemp, "Storage Temperature", :class =>"control-label") %>
		<div class="controls">
			<%= f.text_field :storagetemp%>
		</div>
	</div>
  
	<div class="form-actions">
		<%= f.submit :class => "btn-primary" %>
	</div>
<fieldset>
<% end %>

app/views/iqcs/add_ams_qc.html.erb
<% if @iqc == false %>
	<div id="error_explanation">
		<div class="alert alert-error">
		Error Adding Record
		</div>
	</div>
<% else %>
<div class="alert alert-success">
Record Imported
</div>
<% end %>

app/views/iqcs/ams_qc.html.erb
<div class="row">
  <div class="span6">
	<span class="label label-success">IQC Materials In System</span></br>
	<ul>
  	<% @iqc.each do |iqc| %>
		<li><%=iqc.lotno%></li>
	<%end%>
	</ul>
  </div>

<div class="span6">
	<span class="label label-success">IQC Materials in AMS</span></br>
	<ul>
  	<% @ams.each do |ams| %>
		<li><%=ams.qclot%></li>
	<%end%>
	</ul>
  </div>
</div>
<div class="row">
	<% if @diffs.empty? %>
	<div class="alert alert-success">
		No differences found
		</div>
		<%else%>
		Differences: <%=@diffs%>
		<%= link_to "Add unimported IQC Material", iqcs_add_ams_qc_path(:qc_lot => @diffs[0].qclot) %>
		<%end%>	
</div>

app/views/iqcs/edit.html.erb
<h1>Editing iqc</h1>

<%= render 'form' %>

<%= link_to 'Show', @iqc, :class=>"btn btn-inverse" %> |
<%= link_to 'Back', iqcs_path, :class=>"btn btn-inverse" %>

app/views/iqcs/generate.html.erb
Auto Generated the following qcs:<br>
<table class="table table-bordered table-striped table-condensed table-hover">
  <tr>
    <th>QC Lot</th>
  </tr>

<% @geniqc.each do |qc| %>
  <tr>
	<td><%= qc.qclot %> </td>
  </tr>
<% end %>
</table>

app/views/iqcs/index.html.erb
<h2>Listing IQC Materials</h2>

<table class="table table-bordered table-striped table-hover table-condensed">
<thead>
  <tr>
    <th>Material Name</th>
    <th>Manufacturer</th>
    <th>Notes</th>
	<th>Code</th>
    <th>Lot Number</th>
    <th>Expiry Date</th>
	<th>Storage Location</th>
    <th>Storage Temperature</th>
    <th>Date in Use</th>
	<th>Date Reconstituted</th>
    <th>Number Of Aliquots</th>
    <th>Made Up By</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>

<tfoot>
    	<tr>
        	<td colspan="8" class="rounded-foot-left"><em>IQC Materials</em></td>
        	<td class="rounded-foot-right">&nbsp;</td>
        </tr>
</tfoot>


<% @iqc.each do |iqc| %>
<% unless iqc.expirydate.nil? %>
<% if iqc.expirydate.to_formatted_s(:long) > Date.today.to_formatted_s(:long) then%>
  <tr class='error'>
<%else%>
  <tr>
<%end%>
<%end%>
    <td><%= iqc.name %></td>
    <td><%= iqc.manufacturer %></td>
    <td><%= iqc.notes %></td>
    <td><%= iqc.code %></th>
    <td><%= iqc.lotno %></th>
	<td><% unless iqc.expirydate.nil? 
				iqc.expirydate.to_formatted_s(:long) 
		   end %> </td>
	<td><%= iqc.storagelocation %> </th>
    <td><%= iqc.storagetemp %> </th>
    <td><% 	unless iqc.expirydate.nil? 
	 			iqc.dateinuse.to_formatted_s(:long) 
			end %></th>
	<td><% 	unless iqc.expirydate.nil? 
				iqc.datereconstituted.to_formatted_s(:long) 
			end %></th>
    <td><%= iqc.numberofaliquots %></th>
   	<td><%# 	unless iqc.expirydate.nil? 
					User.find(iqc.users_id).email 
			end %></th> 
	
    <td><%= link_to 'Show', iqc, :class => "btn btn-info btn-mini" %></td>
    <td><%= link_to 'Edit', edit_iqc_path(iqc), :class => "btn btn-primary btn-mini" %></td>
    <td><%= link_to 'Destroy', iqc, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-mini" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Iqc', new_iqc_path, :class => "btn btn-primary" %></td>

app/views/iqcs/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', iqcs_path, :class=>"btn btn-inverse" %>

app/views/iqcs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @iqc.name %>
</p>

<p>
  <b>Manufacturer:</b>
  <%= @iqc.manufacturer %>
</p>

<p>
  <b>Notes:</b>
  <%= @iqc.notes %>
</p>

<p>
  <b>Assigned:</b>
  <%= @iqc.assigned %>
</p>

<p>
  <b>Record Created:</b>
  <%= @iqc.created_at %>
</p>


<%= link_to 'Edit', edit_iqc_path(@iqc), :class=>"btn btn-success" %> |
<%= link_to 'Back', iqcs_path, :class=>"btn btn-inverse" %>