config/routes.rb
Performance::Application.routes.draw do
  resources :analyser_classes
  resources :analyser_types
  resources :create_analyser_types
  resources :form_configs
  match 'eqaform/:form_builder_id' => 'form_configs#create_form'
  
  resources :form_configs do
    resources :form_configs
  end
  
  resources :form_builders
  devise_for :admins
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :eqa_schemes
  
  resources :change_loggings 
  match 'change_loggings_deleteall' => 'change_loggings#deleteall'
  
  resources :eqas
  match 'create_eqa_form' => 'eqas#create_eqa_form'
  
  resources :quality_specifications 
  resources :quality_specification_imports
  
  
  
  get 'test_codes/add_ams_test_codes', to: 'test_codes#add_ams_test_codes'
  get 'test_codes/ams_test_codes', to: 'test_codes#ams_test_codes'
  get "test_codes/new"
  get "test_codes/create"
  match 'test_generate' => 'test_codes#generate'
  resources :test_code_imports
  resources :test_codes
  
  match 'sigmacalc' => 'sigmas#calculateSigmas'
  match 'sigmaplot' => 'sigmas#plotSigmas'
  match 'alltestssigma' => 'sigmas#allTestsSigmaPlot'
  resources :sigmas
  
  get 'iqc_data/analyser_iqc', to: 'iqc_data#analyser_iqc'
  get 'iqc_data/view', to: 'iqc_data#view'
  get 'iqc_data/show_analyser/', to: 'iqc_data#show_analyser_view'
  post 'iqc_data/show_analyser/', to: 'iqc_data#show_analyser_view'
  get 'iqc_data/show_iqc_material_view', to: 'iqc_data#show_iqc_material_view'
  get 'iqc_data/show_test_view', to: 'iqc_data#show_test_view'
  
  resources :iqc_data
  
  get 'iqcs/add_ams_qc', to: 'iqcs#add_ams_qc'
  get 'iqcs/ams_qc', to: 'iqcs#ams_qc'
  
  resources :iqcs
  resources :targets
  
  match 'transfer_qc' => 'iqc_data#transfer'
  
  match 'iqc_data/test_view' => 'iqc_data#test_view'
  match 'iqc_data/view_iqc_stats' => 'iqc_data#view_iqc_stats'
  match 'iqc_data/view_iqc_stats' => 'iqc_data#view_iqc_stats'
  match 'iqc_data/view_analyser_stats' => 'iqc_data#view_analyser_stats'
  
  
  match 'qc_generate' => 'iqcs#generate'
  
  get 'analysers/add_ams_analyser', to: 'analysers#add_ams_analyser'
  get 'analysers/ams_analyser', to: 'analysers#ams_analyser'
  match 'analyser_generate' => 'analysers#generate'
  resources :analysers
  
  resources :imported_file
  resources :imported_qc

  get "home/index"
  match "home/index" =>"home#index"
  root :to => "home#index"

end

app/models/quality_specification.rb
class QualitySpecification < ActiveRecord::Base
  attr_accessible :bias, :imprecision, :test_code_id, :cvi, :cvw, :goaltype, :desirableTE
  
  belongs_to :testCode
  
  validates_presence_of :goaltype, :test_code_id
  
  before_save :calculate_metrics
  
	def self.import(file)
  		spreadsheet = open_spreadsheet(file)
  		header = spreadsheet.row(1)
  		(2..spreadsheet.last_row).each do |i|
    		row = Hash[[header, spreadsheet.row(i)].transpose]
    	quality_specification = find_by_id(row["id"]) || new
    	quality_specification.attributes = row.to_hash.slice(*accessible_attributes)
    	quality_specification.save!
  end
end

	def self.open_spreadsheet(file)
  		case File.extname(file.original_filename)
  			when ".csv" then Csv.new(file.path, nil, :ignore)
  			when ".xls" then Excel.new(file.path, nil, :ignore)
  			when ".xlsx" then Excelx.new(file.path, nil, :ignore)
  		else raise "Unknown file type: #{file.original_filename}"
  		end
	end
  
def self.to_csv(options = {})
  CSV.generate(options) do |csv|
    csv << column_names
    all.each do |specificaiton|
      csv << specificaiton.attributes.values_at(*column_names)
    end
  end
end
  
  # If we have a biological specification then calculate quality metrics on this basis
  def calculate_metrics
    if self.goaltype == "Biological"
      unless self.cvi.blank? || self.cvw.blank?
        #Calculate various quality metrics
        self.allowableCVoptimal = self.cvi * 0.25
        self.allowableCVdesirable = self.cvi * 0.5
        self.allowableCVminimum = self.cvi * 0.75

        self.allowableBIASoptimal =0.125*(self.allowableCVoptimal**2+self.cvw**2)**0.5
        self.allowableBIASdesirable =0.25*(self.allowableCVdesirable**2+self.cvw**2)**0.5
        self.allowableBIASminimum =0.375*(self.allowableCVminimum**2+self.cvw**2)**0.5

        self.minimumTE =1.65*(0.75*self.cvi**2)+0.375*(self.cvi**2+self.cvw**2)**0.5
        self.desirableTE =1.65*(0.5*self.cvi**2)+0.25*(self.cvi**2+self.cvw**2)**0.5
        self.optimalTE = 1.65*(0.25*self.cvi**2)+0.125*(self.cvi**2+self.cvw**2)**0.5
      end
    end
  end
end

app/controllers/quality_specifications_controller.rb
class QualitySpecificationsController < ApplicationController
  
  before_filter :authenticate_user!
  
  
  # GET /quality_specifications
  # GET /quality_specifications.json
  def index
    @quality_specifications = QualitySpecification.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @quality_specifications }
      format.csv { send_data QualitySpecification.to_csv }
      format.xls # { send_data @quality_specifications.to_csv(col_sep: "\t")}
    end
  end

  # GET /quality_specifications/1
  # GET /quality_specifications/1.json
  def show
    @quality_specification = QualitySpecification.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @quality_specification }
    end
  end

  # GET /quality_specifications/new
  # GET /quality_specifications/new.json
  def new
    @quality_specification = QualitySpecification.new


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @quality_specification }
    end
  end

  # GET /quality_specifications/1/edit
  def edit
    @quality_specification = QualitySpecification.find(params[:id])
  end

  # POST /quality_specifications
  # POST /quality_specifications.json
  def create
    @quality_specification = QualitySpecification.new(params[:quality_specification])

    respond_to do |format|
      if @quality_specification.save
        @quality_specification.users_id = current_user.id
        changeLogging = ChangeLogging.new(:logRecord => 'Quality Specification Entered', :users_id => current_user.id)
        changeLogging.save
        
        
        format.html { redirect_to @quality_specification, notice: 'Quality specification was successfully created.' }
        format.json { render json: @quality_specification, status: :created, location: @quality_specification }
      else
        format.html { render action: "new" }
        format.json { render json: @quality_specification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /quality_specifications/1
  # PUT /quality_specifications/1.json
  def update
    @quality_specification = QualitySpecification.find(params[:id])

    respond_to do |format|
      if @quality_specification.update_attributes(params[:quality_specification])
        
        @quality_specification.users_id = current_user.id
        changeLogging = ChangeLogging.new(:logRecord => 'Quality Specificaiton Updated', :users_id => current_user.id)
        changeLogging.save
        
        
        format.html { redirect_to @quality_specification, notice: 'Quality specification was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @quality_specification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quality_specifications/1
  # DELETE /quality_specifications/1.json
  def destroy
    @quality_specification = QualitySpecification.find(params[:id])
    @quality_specification.destroy
    
    changeLogging = ChangeLogging.new(:logRecord => 'Quality Specification deleted' + params[:id], :users_id => current_user.id)
    changeLogging.save

    respond_to do |format|
      format.html { redirect_to quality_specifications_url }
      format.json { head :no_content }
    end
  end
  
  def import
  	QualitySpecification.import(params[:file])
  	changeLogging = ChangeLogging.new(:logRecord => 'Quality Specifications imported', :users_id => current_user.id)
    changeLogging.save
  	redirect_to root_url, notice: "Quality specifications imported."
  end
  
  
end

app/views/quality_specifications/_form.html.erb
<%= form_for @quality_specification, :html => {:class => "form-horizontal well"} do |f| %>
  <% if @quality_specification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quality_specification.errors.count, "error") %> prohibited this quality_specification from being saved:</h2>

      <ul>
      <% @quality_specification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<legend>Add/Edit Quality Specification</legend>
<fieldset>
	<div class="control-group">
		<%= label_tag(:test_code_id, "Test Code", :class =>"control-label") %>
		<div class="controls">
			<%= select("quality_specification", "test_code_id", TestCode.all.collect {|p| [ p.testExpansion, p.id ] }, {:include_blank => 'None'}) %>
		</div>
	</div>
	
	<div class="control-group">
		<%= label_tag(:quality_specification, "Choose Goal Type", :class =>"control-label") %>
		<div class="controls">
			<%= select("quality_specification", "goaltype", [ "Biological", "Clinical", "TE" ], {:include_blank => 'None'}) %>
		 <span class="help-block">For biological specifications enter %Inter and Intra individual %CV <br> %TE and allowable %Bias and %Imprecision will be calculated automatically</span><br>
		<span class="help-block">For Clinical Specifications enter %Bias and %Imprecision</span><br>
		<span class="help-block">For %TE Specifications enter %Total Allowable Error</span>
		</div>
	</div>

	<div class="control-group">
		<%= label_tag(:bias, "Bias", :class =>"control-label") %>
		<div class="controls">
			<%= f.text_field :bias %>
		</div>
	</div>
	
	<div class="control-group">
		<%= label_tag(:imprecision, "Imprecision", :class =>"control-label") %>
		<div class="controls">
			<%= f.text_field :imprecision %>
		</div>
	</div>

	<div class="control-group">
		<%= label_tag(:cvi, "Intra individual %CV", :class =>"control-label") %>
		<div class="controls">
			<%= f.text_field :cvi %>
		</div>
	</div>
	
	<div class="control-group">
		<%= label_tag(:cvw, "Inter individual %CV", :class =>"control-label") %>
		<div class="controls">
			<%= f.text_field :cvw %>
		</div>
	</div>

	<div class="control-group">
		<%= label_tag(:desirableTE, "Desirable %Total Error (%TE)", :class =>"control-label") %>
		<div class="controls">
			<%= f.text_field :desirableTE %>
		</div>
	</div>


	<div class="form-actions">
		<%= f.submit :class => "btn-primary" %>
	</div>
<fieldset>
<% end %>

app/views/quality_specifications/edit.html.erb
<h1>Editing quality_specification</h1>

<%= render 'form' %>

<%= link_to 'Show', @quality_specification, :class=>"btn btn-success" %> |
<%= link_to 'Back', quality_specifications_path, :class=>"btn btn-inverse" %>

app/views/quality_specifications/index.html.erb
<h2>Listing quality specifications currently configured</h2>

<table class="table table-bordered table-striped">
<thead>
  <tr>
    <th>Test Name</th>
    <th>Bias Target</th>
    <th>Imprecision Target</th>
	<th>Intra Individual %CV</th>
	<th>Inter Individual %CV</th>
	<th>Specification Type</th>
    <th>Editing</th>
    <th></th>
    <th></th>
  </tr>
</thead>
<tfoot>
    	<tr>
        	<td colspan="9"><em>Quality specifications</em></td>
        </tr>
 </tfoot>

<% @quality_specifications.each do |quality_specification| %>

</td>

  <tr>
    <td><%= render  'common/test_code_id', :object => quality_specification.test_code_id %></td>
    <td><%= quality_specification.bias %></td>
    <td><%= quality_specification.imprecision %></td>
	<td><%= quality_specification.cvi %></td>
	<td><%= quality_specification.cvw %></td>
	<td><%= quality_specification.goaltype %></td>
    <td><%= link_to 'Show', quality_specification, :class =>"btn btn-info btn-small" %></td>
    <td><%= link_to 'Edit', edit_quality_specification_path(quality_specification), :class => "btn btn-primary btn-small" %></td>
    <td><%= link_to 'Destroy', quality_specification, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-small" %></td>
  </tr>
<% end %>
</table>

<p>How good does a test need to be? Answering this question will help determine the total allowable error (TEa); the amount of error a test has and is still considered "in control." The laboratory can use several models to determine quality requirements:</p>

<p>Medical usefulness requirements based on the effect of analytical performance on clinical decisions such as:</p>
<ul>
<li>Biological variation information.</li>
<li>Clinicians&#8217; opinions.</li>
<li>Published professional recommendations from:</li>
<li>National and international expert bodies and agencies.</li>
<li>Expert local groups or individuals.</li>
<li>Performance goals set by:</li>
<li>Regulatory bodies and agencies.</li>
<li>Organizers of External Quality Assessment (EQA) schemes.</li>
<li>Goals based on the current state of the art, which include:</li>
<li>Interlaboratory comparison programs such as the Unity™ Interlaboratory Program.</li>
<li>EQA or proficiency testing schemes.</li>
<li>Current published information on methodology.</li>
</ul>

<p>The preceding hierarchy is based on the consensus agreement published in the Scandinavian Journal of Clinical and Laboratory Investigation 1999; 59: 585.</p>

<p> Sigma = [(%TEa – %bias)/%CV]</p>

<p>
  Download:
  <%= link_to "CSV", quality_specifications_path(format: "csv") %> |
  <%= link_to "Excel", quality_specifications_path(format: "xls") %>
</p>
<br />

<p><%= link_to "New Quality Specifications", new_quality_specification_path, :class =>"btn btn-primary" %></p>
<p><%= link_to "Import Quality Specifications", new_quality_specification_import_path,:class =>"btn btn-primary" %></p>

app/views/quality_specifications/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', quality_specifications_path, :class=>"btn btn-inverse" %>

app/views/quality_specifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Test Name:</b>
  <td><%= render  'common/test_code_id', :object => @quality_specification.test_code_id %></td>
</p>

<p>
  <b>Bias Target:</b>
  <%= @quality_specification.bias %>
</p>

<p>
  <b>Imprecision Target:</b>
  <%= @quality_specification.imprecision %>
</p>


<%= link_to 'Edit', edit_quality_specification_path(@quality_specification), :class=>"btn btn-success" %> |
<%= link_to 'Back', quality_specifications_path, :class=>"btn btn-inverse" %>